require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/competencies", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Competency. As you add validations to Competency, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Competency.create! valid_attributes
      get competencies_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      competency = Competency.create! valid_attributes
      get competency_url(competency)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_competency_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      competency = Competency.create! valid_attributes
      get edit_competency_url(competency)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Competency" do
        expect {
          post competencies_url, params: { competency: valid_attributes }
        }.to change(Competency, :count).by(1)
      end

      it "redirects to the created competency" do
        post competencies_url, params: { competency: valid_attributes }
        expect(response).to redirect_to(competency_url(Competency.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Competency" do
        expect {
          post competencies_url, params: { competency: invalid_attributes }
        }.to change(Competency, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post competencies_url, params: { competency: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested competency" do
        competency = Competency.create! valid_attributes
        patch competency_url(competency), params: { competency: new_attributes }
        competency.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the competency" do
        competency = Competency.create! valid_attributes
        patch competency_url(competency), params: { competency: new_attributes }
        competency.reload
        expect(response).to redirect_to(competency_url(competency))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        competency = Competency.create! valid_attributes
        patch competency_url(competency), params: { competency: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested competency" do
      competency = Competency.create! valid_attributes
      expect {
        delete competency_url(competency)
      }.to change(Competency, :count).by(-1)
    end

    it "redirects to the competencies list" do
      competency = Competency.create! valid_attributes
      delete competency_url(competency)
      expect(response).to redirect_to(competencies_url)
    end
  end
end
